#!/bin/zsh

fonts=("JetBrainsMono")
nerd_fonts_dir="${HOME}/nerd-fonts"

function clone_nerd_fonts()
{
[ ! -d "${nerd_fonts_dir}" ] && git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git "${nerd_fonts_dir}"
}

function install_nerd_fonts()
{
eval "${nerd_fonts_dir}/install.sh" "${fonts[@]}"
}

"$1"

