#!/bin/zsh
set -e

packages=(i3-gaps
    i3lock
    alacritty
    dunst
    fd
    stow
    bat
    htop
    noto-fonts-emoji
    neovim
    python-pynvim
    picom
    playerctl
    rofi
    ripgrep
    zathura
    zathura-pdf-mupdf
    xss-lock
    xorg-xinit
    xorg
    fzf
    xsel
    networkmanager-manager-applet
    libnotify
    alsa-utils
    flameshot
    mate-icon-theme
    nitrogen
    zsh
    which
    wget
    mlocate
    lxappearance
    exa
    ctags
    imagemagick
    namcap
    xdotool
    bc
    jq
    tlp
    vlc
    feh
    sxiv
)

aur_packages=(spotify
    antigen-git
    ccls-git
    rofi-greenclip
    devour
    google-chrome
)

function install_paru()
{
    rm -rf ~/paru
    git clone https://aur.archlinux.org/paru-bin.git ~/paru
    cd ~/paru
    makepkg -si
    rm -rf ~/paru
}

function install_aur()
{
    paru -S --noconfirm "${aur_packages[@]}"
}

function install_packages()
{
    pacman -S --noconfirm "${packages[@]}"
}

function install_i3blocks_contrib()
{
    local loc="$HOME/.i3blocks-contrib"
    rm -rf $loc
    git clone git@github.com:pabloariasal/i3blocks-contrib.git $loc
    cd $loc
    git remote add upstream https://github.com/vivien/i3blocks.git
}

function install_wallpapers()
{
    local wallpaper_loc="$HOME/wallpapers"
    git clone https://gitlab.com/dwt1/wallpapers.git $wallpaper_loc
}

"$1"
