#!/bin/zsh
set -e

packages=(i3-gaps
    i3lock
    alacritty
    dunst
    fd
    stow
    bat
    htop
    noto-fonts-emoji
    neovim
    python-pynvim
    picom
    playerctl
    ripgrep
    zathura
    zathura-pdf-mupdf
    xss-lock
    xorg-xinit
    xorg
    fzf
    xsel
    networkmanager-manager-applet
    libnotify
    alsa-utils
    flameshot
    mate-icon-theme
    nitrogen
    zsh
    which
    wget
    mlocate
    lxappearance
    exa
    ctags
    imagemagick
    xdotool
    jq
    tlp
    vlc
    sxiv
    pulseaudio
    pulseaudio-alsa
)

aur_packages=(spotify
    ccls-git
    devour
    google-chrome
)

function install_patched_dmenu()
{
    git clone git@github.com:pabloariasal/dmenu.git
    cd dmenu
    make
    sudo make install
}

function install_paru()
{
    rm -rf ~/paru
    git clone https://aur.archlinux.org/paru-bin.git ~/paru
    cd ~/paru
    makepkg -si
    rm -rf ~/paru
}

function install_aur()
{
    paru -S --noconfirm "${aur_packages[@]}"
}

function install_packages()
{
    pacman -S --noconfirm "${packages[@]}"
}

function install_wallpapers()
{
    local wallpaper_loc="$HOME/wallpapers"
    git clone https://gitlab.com/dwt1/wallpapers.git $wallpaper_loc
}

function install_nerd_fonts()
{
    local nerd_fonts_dir="$HOME/nerd-fonts"
    [ ! -d "$nerd-fonts" ] || git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git $nerd_fonts_dir
    cd "$HOME/nerd-fonts"
    ./install.sh JetBrainsMono
}

function install_i3lock_fancy()
{
    mkdir -p ~/tools
    cd ~/tools
    git clone https://github.com/guimeira/i3lock-fancy-multimonitor.git
    chmod +x ${HOME}/tools/i3lock-fancy-multimonitor/lock
    ln -s ${HOME}/tools/i3lock-fancy-multimonitor/lock ${HOME}/bin/i3lock-fancy
}

"$1"
