#!/bin/zsh

# ShareTechMono
# MPlus
# FiraCode
# IBMPlexMono
# HeavyData
# Hermit
# DejaVuSansMono
# FiraMono
# Hasklig
# 3270
# InconsolataGo
# BitstreamVeraSansMono
# Overpass
# Ubuntu
# CascadiaCode
# Go-Mono
# Hack
# SpaceMono
# Monoid
# Arimo
# InconsolataLGC
# ProFont
# Agave
# Gohu
# Mononoki
# Inconsolata
# Terminus
# DaddyTimeMono
# FantasqueSansMono
# UbuntuMono
# Noto
# DroidSansMono
# AurulentSansMono
# SourceCodePro
# BigBlueTerminal
# Cousine
# Meslo
# Lekton
# LiberationMono
# CodeNewRoman
# Monofur
# Iosevka
# Tinos
# AnonymousPro
# JetBrainsMono
# OpenDyslexic
# VictorMono
# RobotoMono
# iA-Writer
# ProggyClean

fonts=("FiraMono")
nerd_fonts_dir="${HOME}/nerd-fonts"

function clone_nerd_fonts()
{
[ ! -d "${nerd_fonts_dir}" ] && git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git "${nerd_fonts_dir}"
}

function install_nerd_fonts()
{
eval "${nerd_fonts_dir}/install.sh" "${fonts[@]}"
}

"$1"

