#!/bin/zsh
set -e

packages=(i3-gaps
    i3lock
    alacritty
    dunst
    fd
    stow
    bat
    htop
    noto-fonts-emoji
    neovim
    picom
    ripgrep
    zathura
    zathura-pdf-mupdf
    xss-lock
    xorg-xinit
    xorg
    fzf
    xsel
    networkmanager
    networkmanager-manager-applet
    libnotify
    alsa-utils
    flameshot
    nitrogen
    zsh
    which
    wget
    mlocate
    exa
    ctags
    imagemagick
    xdotool # needed for scratchpad terminal
    tlp
    vlc
    pulseaudio
    pulseaudio-alsa
    gnome-themes-extra
)

aur_packages=(spotify
    devour
    google-chrome
)

function install_patched_dmenu()
{
    local tools_dir=${HOME}/tools
    mkdir -p ${tools_dir}
    cd ${tools_dir}
    git clone git://git.suckless.org/dmenu
    cd dmenu
    wget https://tools.suckless.org/dmenu/patches/case-insensitive/dmenu-caseinsensitive-5.0.diff -O patch1
    patch < patch1
    wget https://gist.githubusercontent.com/pabloariasal/6b41324165613ce346c0242daa4a09e1/raw/df71daa361b2ac96e1a02763781bf4e2fd9ac006/gistfile1.txt -O patch2
    patch < patch2
    make
    sudo make install
}

function install_paru()
{
    rm -rf ~/paru
    git clone https://aur.archlinux.org/paru-bin.git ~/paru
    cd ~/paru
    makepkg -si
    rm -rf ~/paru
}

function install_aur()
{
    paru -S --noconfirm "${aur_packages[@]}"
}

function install_packages()
{
    pacman -S --noconfirm "${packages[@]}"
}

function install_wallpapers()
{
    local wallpaper_loc="$HOME/wallpapers"
    mkdir -p $wallpaper_loc
    git clone https://gitlab.com/dwt1/wallpapers.git $wallpaper_loc/dt
    git clone git@github.com:pabloariasal/wallpapers.git $wallpaper_loc/me
}

function install_nerd_fonts()
{
    local nerd_fonts_dir="$HOME/.nerd-fonts"
    [ -d "$nerd-fonts" ] || git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git $nerd_fonts_dir
    cd "$nerd_fonts_dir"
    ./install.sh JetBrainsMono
}

function install_keyboard_conf()
{
    sudo ln -s ${DOTFILES}/extra/00-keyboard.conf /etc/X11/xorg.conf.d/
}

function enable_agent_service()
{
   systemctl --user enable ssh-agent.service
   systemctl --user start ssh-agent.service
}

"$1"
