#!/bin/zsh

set -e

function install_paru()
{
    rm -rf ~/paru
    git clone https://aur.archlinux.org/paru-bin.git ~/paru
    cd ~/paru
    makepkg -si
    rm -rf ~/paru
}

function install_wallpapers()
{
    local wallpaper_loc="$HOME/wallpapers"
    rm -rf "$wallpaper_loc"
    mkdir -p $wallpaper_loc
    cd "$wallpaper_loc"
    [ ! -d dt ] && git clone https://gitlab.com/dwt1/wallpapers.git dt
    [ ! -d gruvbox ] && git clone https://github.com/mTvare6/gruvbox-wallpaper.git gruvbox
    [ ! -d me ] && git clone git@github.com:pabloariasal/wallpapers.git me
}

function install_nerd_fonts()
{
    local nerd_fonts_dir="$HOME/nerd-fonts"
    [ -d "$nerd-fonts" ] || git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git $nerd_fonts_dir
    cd "$nerd_fonts_dir"
    ./install.sh JetBrainsMono DejaVuSansMono
}

function install_scripts() {
    cd "$DOTFILES"
    stow --verbose=2 -d configs -t ~ scripts
    stow --verbose=2 -d configs -t ~ scripts-wm
    stow --verbose=2 -d configs -t ~ webapps
}

function install_pulseaudio() {
    sudo pacman -S pulseaudio \
        pavucontrol \
        pulseaudio-alss
}

function install_cpp_dev_tools() {
    sudo pacman -S ccache clang cmake ninja
}

function install_keyboard_conf()
{
    sudo ln -s ${DOTFILES}/extra/00-keyboard.conf /etc/X11/xorg.conf.d/
}

function enable_agent_service()
{
   systemctl --user enable ssh-agent.service
   systemctl --user start ssh-agent.service
}

function install_command_line_goodies() {
    sudo pacman -S fd ripgrep vifm fzf bat eza
}

function install_devour()
{
    mkdir -p ${HOME}/tools
    cd ${HOME}/tools
    rm -rf devour
    git clone https://github.com/salman-abedin/devour.git
    cd devour
    sudo make install
}

function install_git_worktree_relative()
{
    cd /tmp
    rm -rf git-worktree-relative
    git clone https://github.com/Kristian-Tan/git-worktree-relative.git
    cd git-worktree-relative
    [[ -e ~/.local/bin/git-worktree-relative ]] && bash -- uninstall.sh ~/.local/bin
    bash -- install.sh ~/.local/bin
}

function create_github_personal_ssh_key()
{
    mkdir -p ~/.ssh
    ssh-keygen -t ed25519 -C "pabloariasal@gmail.com" -f ~/.ssh/github_personal
    xclip -selection clipboard < ~/.ssh/github_personal.pub
    echo "copied public key to clipboard!"
}

function install_greenclip() {
    rm -f ~/.local/bin/greenclip
    wget -P ~/.local/bin https://github.com/erebe/greenclip/releases/download/v4.2/greenclip
    chmod +x ~/.local/bin/greenclip
}

function install_python_language_server() {
    sudo pacman -S python-pip \
        python-lsp-server \
        python-pyflakes \
        python-pycodestyle \
        yapf \
        python-pylint
}

function install_xorg() {
    sudo pacman -S xorg-server \
        xorg-xev \
        xdotool \
        xorg-xmodmap \
        xorg-xrand \
        arandr
}

function install_i3_wm() {
    sudo pacman -S i3-wm \
        i3lock \
        i3status \ 
        bemenu \
        xss-lock \
        jq \
        dunst \
        noto-fonts-emoji
}

function clone_repo() {
    git clone git@github.com:pabloariasal/dotfiles.git ~/dotfiles
}

if [[ $# -eq 0 || "$*" == *"--help"* ]]; then
    SCRIPTPATH="$(realpath "$0")"
    cat "$SCRIPTPATH" | grep 'function' | head -n -1 | awk '{print $2}' | tr -d '()'
    exit 0
fi

"$@"
