vim.cmd('runtime general.vim')
require("config.plugins")
require("config.options")
require("config.autocommands")
require("config.key_maps")
require("config.snippets")
require("config.statusline")
require("config.lsp")
require("config.completion")
require("config.treesitter")
require("config.treesitter-textobjects")
require("config.telescope")
require("config.gitsigns")
require("config.colors")
require("config.user-commands")
require("config.hardtime")
require("config.harpoon")
