#!/usr/bin/env bash

options="
https://www.youtube.com\n
https://www.dazn.com\n
https://web.whatsapp.com\n
https://old.reddit.com\n
https://feedly.com\n
https://news.ycombinator.com\n
https://keep.google.com\n
https://mm.navvis.com\n
https://twitter.com\n
"

selection=$(echo -e $options | rofi -dmenu)
[ ! -z "$selection" ] && chromium --new-window --app="$selection"
