#!/bin/bash
layouts=('us' 'de' 'es')

# current_layout=$(setxkbmap -query | sed -E 's/layout:\s+([a-z]{2})/\1/')
current_layout=$(setxkbmap -query | grep 'layout' | sed -E 's/^layout:\s+([a-z]{2})$/\1/')
# echo $current_layout

for i in ${!layouts[@]}; do
		if [ ${layouts[$i]} == $current_layout ]; then
				new_layout=""
				if [ $(( $i + 1 )) -ge ${#layouts[@]} ];
				then
						new_layout=${layouts[0]}
				else
						new_layout=${layouts[$(( $i + 1 ))]}
				fi
				setxkbmap "$new_layout"
				dunstify -a "notify_layout" -u low -i input-keyboard-symbolic -r "8237" "$new_layout"
		fi
done
