#!/bin/bash

# Arbitrary but unique message id
msgId="99154"

brightness=$(xbacklight | cut -f1 -d ".")
dunstify -a "brightness-change" -u low -i display-brightness-symbolic -r "$msgId" \
    "Brightness: ${brightness}%" "$(getProgressString 10 "<b> </b>" " " $brightness)"

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changedBrightness"
