#!/bin/bash

options="status\nconnect\ndisconnect"
vpn_connection_name="nv-pf1-udp-1194-Pablo_Arias"
title="VPN"

# Get user selection via dmenu from emoji file.
chosen=$(echo -e $options | rofi -dmenu -i)

# Exit if none chosen.
[ -z "$chosen" ] && exit

case "$chosen" in
    "connect")
        output="$(nmcli c up ${vpn_connection_name} 2>&1)"
        notify-send "$title" "$output"
        ;;
    "disconnect")
        output="$(nmcli c down ${vpn_connection_name} 2>&1)"
        notify-send "$title" "$output"
        ;;
    *)
        vpn="$(nmcli -t -f name,type connection show --order name --active 2>/dev/null | grep vpn | head -1 | cut -d ':' -f 1)"
        if [ -n "$vpn" ]; then
            notify-send "$title" "$vpn connected!"
        else
            notify-send "$title" "No VPN connected!"
        fi
        ;;
esac
