#!/bin/bash
title="VPN Status"
vpn="$(nmcli -t -f name,type connection show --order name --active 2>/dev/null | grep vpn | head -1 | cut -d ':' -f 1)"
if [ -n "$vpn" ]; then
    notify-send "$title" "$vpn connected!"
else
    notify-send "$title" "No VPN connected!"
fi
