alias n='nvim'
alias b='bat'
alias sudo='sudo '
alias p='pacman'
alias ls='ls --color=tty'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'
alias -- -='cd -'
alias ..='cd ..'

# Git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gapa='git add --patch'
alias gau='git add --update'
alias gc='git commit -v'
alias 'gca'='git commit -v --amend'
alias 'gcan'='git commit -v --no-edit --amend'
alias gcb='git checkout -b'
alias gco='git checkout'
alias gd='git diff'
alias gdca='git diff --cached'
alias gf='git fetch'
alias gka='\gitk --all --branches'
alias gk='\gitk'
alias gl='git log'
alias glp='git log --stat -p'
alias glo='git log --oneline --decorate'
alias gm='git merge'
alias gp='git push'
alias 'gp!'='git push --force'
alias grb='git rebase'
alias gs='git status'
alias gsta='git stash'
