alias n='nvim'
alias b='bat'
alias sudo='sudo '
alias p='pacman'
alias ls='ls --color=tty'
alias l='ls'
alias ll='ls -lh'
alias la='ls -lAh'
alias ..='cd ..'
alias ipinfo='curl -s ifconfig.co/json | jq'

#devour
alias za='devour zathura'
alias sx='devour sxiv'
alias gka='devour gitk --all --branches'
alias gk='devour gitk'
