#!/bin/zsh

packages=(i3-gaps
    i3lock-color
    alacritty
    dunst
    fd
    bat
    htop
    ncdu
    # required for rofimoji
    noto-fonts-emoji
    neovim
    python-pynvim
    picom
    playerctl
    rofi
    ripgrep
    zathura
    zathura-pdf-mupdf
    xss-lock
    xorg-xinit
    xorg
    fzf
    xsel
    nm-manager-applet
    networkmanager-openvpn
    tree
    # required for coc.nvim
    npm
    ttf-font-awesome
    libnotify
    alsa-utils
    flameshot
    mate-icon-theme
    tk
    vifm
    nitrogen
    nodejs
    zsh
    which
    wget
    mlocate
    lxappearance
    exa
    ctags
    imagemagick
    namcap
    xdotool
    bc
    jq
    tlp
)

aur_packages=(spotify
    antigen-git
    pymodoro-git
    ccls-git
    fast
    python-ueberzug
    xcursor-oxygen
    polybar
    glow
    rofi-greenclip
    hstr
    fontpreview-ueberzug-git
    devour
    dropbox-cli
    dropbox
    google-chrome
)

function paru()
{
    rm -rf ~/paru
    git clone https://aur.archlinux.org/paru-bin.git ~/paru
    cd ~/paru
    makepkg -si
    rm -rf ~/paru
}

function install_aur()
{
    paru -S --noconfirm "${aur_packages[@]}"
}

function install_packages()
{
    pacman -S --noconfirm "${packages[@]}"
}

"$1"
