#!/bin/zsh

packages=(i3-gaps
	i3lock
	alacritty
	chromium
	dunst
	fd
	bat
	feh
	htop
	irssi
	neovim
	picom
	playerctl
	python-pywal
	rofi
	ripgrep
	wavemon
	zathura
	words
	xss-lock
	xorg-xinit
	xorg
	fzf
	xsel
	python-pynvim
	nm-connection-editor
	networkmanager-openvpn
	tree
	npm
	ttf-font-awesome
	libnotify
	alsa-utils
	scrot
	mate-icon-theme
	tk
	nodejs)

aur_packages=(spotify
	antigen-git
	ccls-git
	chromium-widevine
	fast
	gotop-bin
	minetime-bin
	pfetch
	polybar)

function install_yay()
{
rm -rf ~/yay
git clone https://aur.archlinux.org/yay.git ~/yay
cd ~/yay
makepkg -si
}

function install_aur()
{
		yay -S --noconfirm "${aur_packages[@]}"
}

function install_packages()
{
		pacman -S --noconfirm "${packages[@]}"
}

"$1"
