#!/bin/zsh

packages=(i3-gaps
    i3lock-color
    alacritty
    dunst
    fd
    bat
    htop
    figlet
    lolcat
    ncdu
    # required for rofimoji
    noto-fonts-emoji
    irssi
    neovim
    python-pynvim
    picom
    playerctl
    rofi
    ripgrep
    zathura
    zathura-pdf-mupdf
    xss-lock
    xorg-xinit
    xorg
    fzf
    xsel
    nm-manager-applet
    networkmanager-openvpn
    tree
    npm
    ttf-font-awesome
    libnotify
    alsa-utils
    flameshot
    mate-icon-theme
    tk
    vifm
    sxiv
    nitrogen
    nodejs
    zsh
    which
    wget
    mlocate
    lxappearance
    evolution
    evolution-ews
    gnome-keyring
    seahorse
    exa
    ctags
    chromium
    imagemagick
    namcap
    xdotool
    bc
    jq
    tlp
)

aur_packages=(spotify
    antigen-git
    pymodoro-git
    ccls-git
    fast
    python-ueberzug
    xcursor-oxygen
    polybar
    glow
    rofi-greenclip
    hstr
    fontpreview-ueberzug-git
    devour
    pfetch-git
    dropbox-cli
    dropbox
)

function install_yay()
{
    rm -rf ~/yay
    git clone https://aur.archlinux.org/yay.git ~/yay
    cd ~/yay
    makepkg -si
}

function install_aur()
{
    yay -S --noconfirm "${aur_packages[@]}"
}

function install_packages()
{
    pacman -S --noconfirm "${packages[@]}"
}

"$1"
