#!/bin/zsh

if [[ -z "${DOTFILES}" ]]; then
echo "DOTFILES not set!"
exit 1
fi

CONF="${HOME}/.config"

ln -sfv ${DOTFILES}/alacritty.yml ${CONF}
ln -sfv ${DOTFILES}/i3 ${CONF}
ln -sfv ${DOTFILES}/polybar ${CONF}
ln -sfv ${DOTFILES}/nvim ${CONF}
ln -sfv ${DOTFILES}/rofi ${CONF}
ln -sfv ${DOTFILES}/dunst ${CONF}
ln -sfv ${DOTFILES}/ctags ${CONF}
ln -sfv ${DOTFILES}/picom.conf ${CONF}
ln -sfv /usr/share/fzf/key-bindings.zsh ${HOME}/.fzf-key-bindings.zsh
ln -sfv /usr/share/zsh/share/antigen.zsh ${HOME}/.antigen.zsh
ln -sfv ${DOTFILES}/xinitrc ${HOME}/.xinitrc
ln -sfv ${DOTFILES}/zprofile ${HOME}/.zprofile
ln -sfv ${DOTFILES}/zshrc ${HOME}/.zshrc
ln -sfv ${DOTFILES}/vifm/vifmrc ${CONF}/vifm/vifmrc
ln -sfv ${DOTFILES}/gitconfig ${HOME}/.gitconfig
ln -sfv ${DOTFILES}/greenclip.cfg ${CONF}
ln -sfv ${DOTFILES}/hstr_favorites ${HOME}/.hstr_favorites
ln -sfv ${DOTFILES}/systemd/user/ssh-agent.service ${CONF}/systemd/user/ssh-agent.service
sudo ln -sfv ${DOTFILES}/pacman.conf /etc/pacman.conf
